### ISSUE TITLE
Add a Favicon to the website

### ISSUE THREAD

**Issue by Kartik9250** [atom-robotics-lab/atom-robotics-lab.github.io#18]

**Comment by Deevyn9** [comment]
Hi, can you assign this issue to me?

**Comment by irfen-mi** [comment]
@Kartik9250 its took 2 minutes assign me this i will add favicon on website.

**Comment by Kartik9250** [comment]
Hello, thanks for reaching out.

@Deevyn9 @developer-irfan do you guys know about Hugo?

**Comment by Kartik9250** [comment]
You can find the logo assets at https://github.com/atom-robotics-lab/assets

**Comment by Deevyn9** [comment]
Hi, I'm done can you merge?

**Comment by Kartik9250** [comment]
@Deevyn9 We have suggested some changes please check the comment on your PR

**Comment by jasmeet0915** [comment]
Solved with #19
