### ISSUE TITLE
Replace Project gifs with Embedded YouTube videos 

### ISSUE THREAD

**Issue by jasmeet0915** [atom-robotics-lab/atom-robotics-lab.github.io#23]
- [x] Embed Youtube videos to our different project pages before the text starts. The videos can be found from our [YouTube Channel](https://www.youtube.com/channel/UCMGzre9_yk8R42rBfu9gO1A).
- [x] Also remove the `.gifs` from `/static/images/projects` that are not needed.
- [x] Remove the youtube links from the text since the video will be embedded on the page itself.

# Implementation suggestion
Use hugo shortcodes for embedding youtube video
```html
{{<youtube yt_video_id>}}
```

**Comment by tiasaxena** [comment]
I want to work on this issue. Assign it to me.

**Comment by darshikaguptaa** [comment]
I want to work on this issue.
Please assign this issue to me.

**Comment by jasmeet0915** [comment]
Solved in #27
