### ISSUE TITLE
Add the missing `arrow-down` icon in Projects page

### ISSUE THREAD

**Issue by jasmeet0915** [atom-robotics-lab/atom-robotics-lab.github.io#24]
The Projects page seems to be missing the arrow-down icon (shown below)

![Screenshot from 2022-10-03 20-50-05](https://user-images.githubusercontent.com/23265149/193614558-5c7e5063-68a9-4344-8a52-72ffd1394003.png)

**Comment by Chaitanya-087** [comment]
hi! i would like to work on this

**Comment by tiasaxena** [comment]
I want to work on this issue. Please assign it to me

**Comment by darshikaguptaa** [comment]
Hey,
I am interested in working on this issue.
Please assign this issue to me

**Comment by tiasaxena** [comment]
This issue has been resolved in #1 (https://github.com/atom-robotics-lab/roxo-hugo/pull/1)
