### ISSUE TITLE
Make links in the Projects section open in a new tab when clicked

### ISSUE THREAD

**Issue by jasmeet0915** [atom-robotics-lab/atom-robotics-lab.github.io#25]
When clicked, the links in the projects page just open in the same tab. Change the markdown to update the links to open in a new tab

**Comment by Abhirv08** [comment]
@jasmeet0915 I would like to solve this issue. Please assign it to me.

**Comment by jasmeet0915** [comment]
@Abhirv08 Yeah Sure!

**Comment by Abhirv08** [comment]
@jasmeet0915 I am facing a little problem with installation in HUGO. Is it necessary to download this? Please help.

**Comment by jasmeet0915** [comment]
@Abhirv08 Our website uses hugo to generate the HTML from the markdown files. You would need it to build the website and test it out locally. So basically it is needed for making and verifying changes to website.
What issues are you facing?

**Comment by Abhirv08** [comment]
Which package management should I choose, Chocolatey or Scoop and then which one extended or simple?

**Comment by jasmeet0915** [comment]
@Abhirv08 I would suggest you go with the extended version for Hugo as it provides support for SCSS. 
As for the package manager, I won't be able to provide a good suggestion as I don't use Windows and am not familiar with either of them. But I would suggest you go with the one you are comfortable with.

**Comment by HazorTremz** [comment]
done
