### ISSUE TITLE
Remove the Contact page and replace its links with a `linktree`

### ISSUE THREAD

**Issue by jasmeet0915** [atom-robotics-lab/atom-robotics-lab.github.io#26]
The website contains a `Connect with us` button on the home page and a `Get in touch` button on the nav bar. Both of these point to the contact page which is not really needed. So it would be better to remove that page entirely and have these buttons point to a linktree with our following socials: 
 * discord 
 * Instagram 
 * youtube
 * twitter.

**Comment by rk-1620** [comment]
@jasmeet0915 I would like to solve this issue. Please assign it to me.

**Comment by racky7** [comment]
@jasmeet0915 I want to work on this.

**Comment by topguns837** [comment]
@jasmeet0915 Can I work on this issue ?

**Comment by jasmeet0915** [comment]
@topguns837 yeah sure

**Comment by topguns837** [comment]
Generated a Pull Request #28 for resolving this issue

**Comment by HazorTremz** [comment]
done
