### ISSUE TITLE
Error in Tab name of project section 

### ISSUE THREAD

**Issue by jchaudhary21** [atom-robotics-lab/atom-robotics-lab.github.io#30]
**How to recreate :**
    Follow this link : https://atom-robotics-lab.github.io/portfolio/
                                                or 
   https://atom-robotics-lab.github.io >> projects (on top)                    

**Change needed :**
                  Change current text : " We at <span> A.T.O.M .... " to Project Section 

![ss atom](https://user-images.githubusercontent.com/96059006/204004530-2871b631-2c15-4b56-9fdb-068196b6efaf.png)

**Comment by jasmeet0915** [comment]
closing the issue since cannot be observed
